const Menu = [
  {
    id: 1,
    category: "breakfast",
    name: "maggi",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$10",
    other: "*Price may vary on selected date",
  },
  {
    id: 2,
    category: "evening",
    name: "allu pakoda",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$20",
    other: "*Price may vary on selected date",
  },
  {
    id: 3,
    category: "lunch",
    name: "piza",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$30",
    other: "*Price may vary on selected date",
  },
  {
    id: 4,
    category: "dinner",
    name: "non-veg thali",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$200",
    other: "*Price may vary on selected date",
  },
  {
    id: 5,
    category: "breakfast",
    name: "sproutes",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$10",
    other: "*Price may vary on selected date",
  },
  {
    id: 6,
    category: "lunch",
    name: "chola",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$15",
    other: "*Price may vary on selected date",
  },
  {
    id: 7,
    category: "evening",
    name: "chai",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$5",
    other: "*Price may vary on selected date",
  },
  {
    id: 8,
    category: "dinner",
    name: "veg thali",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$150",
    other: "*Price may vary on selected date",
  },
  {
    id: 9,
    category: "breakfast",
    name: "juice",
    discription: "Lorem ipsum dolor sit amet consectetur adipisicing elit",
    price: "$20",
    other: "*Price may vary on selected date",
  },
];

export default Menu;
